CREATE TABLE FAMILIAS (
    codFam VARCHAR2(6),
    nomFam VARCHAR2(20)
);

CREATE TABLE ARTICULOS (
    referArt VARCHAR2(6),
    nomArt VARCHAR2(20),
    precio NUMBER(4),
    codFam VARCHAR2(6) NOT NULL
);

CREATE TABLE FACTURAS (
    numFac VARCHAR2(6),
    codCli VARCHAR2(6) NOT NULL
);

CREATE TABLE CLIENTES (
    codCli VARCHAR2(6),
    nomCli VARCHAR2(20),
    apeCli VARCHAR2(20),
    dni VARCHAR2(9)
);

CREATE TABLE LINEAS_FACTURAS (
    referArt VARCHAR2(6) NOT NULL,
    numFac VARCHAR2(6) NOT NULL,
    cantidad NUMBER(4)
);

COMMIT;

ALTER TABLE FAMILIAS ADD CONSTRAINT PK_FAMILIAS PRIMARY KEY (codFam);
ALTER TABLE ARTICULOS ADD CONSTRAINT PK_ARTICULOS PRIMARY KEY (referArt);
ALTER TABLE FACTURAS ADD CONSTRAINT PK_FACTURAS PRIMARY KEY (numFac);
ALTER TABLE CLIENTES ADD CONSTRAINT PK_CLIENTES PRIMARY KEY (codCli);
ALTER TABLE LINEAS_FACTURAS ADD CONSTRAINT PK_LINEAS_FACTURAS PRIMARY KEY (referArt,numFac);

COMMIT;

ALTER TABLE ARTICULOS ADD CONSTRAINT FK_ARTICULOS_FAMILIAS FOREIGN KEY (codFam) REFERENCES FAMILIAS (codFam);
ALTER TABLE FACTURAS ADD CONSTRAINT FK_FACTURAS_CLIENTES FOREIGN KEY (codCli) REFERENCES CLIENTES (codCli);
ALTER TABLE LINEAS_FACTURAS ADD CONSTRAINT FK_LINEAS_FACTURAS_ARTICULOS FOREIGN KEY (referArt) REFERENCES ARTICULOS (referArt);
ALTER TABLE LINEAS_FACTURAS ADD CONSTRAINT FK_LINEAS_FACTURAS_FACTURAS FOREIGN KEY (numFac) REFERENCES FACTURAS (numFac);

COMMIT;