package model;
// Generated Nov 21, 2023 1:50:06 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Facturas generated by hbm2java
 */
public class Facturas  implements java.io.Serializable {


     private String numfac;
     private Clientes clientes;
     private Set lineasFacturases = new HashSet(0);

    public Facturas() {
    }

	
    public Facturas(String numfac, Clientes clientes) {
        this.numfac = numfac;
        this.clientes = clientes;
    }
    public Facturas(String numfac, Clientes clientes, Set lineasFacturases) {
       this.numfac = numfac;
       this.clientes = clientes;
       this.lineasFacturases = lineasFacturases;
    }
   
    public String getNumfac() {
        return this.numfac;
    }
    
    public void setNumfac(String numfac) {
        this.numfac = numfac;
    }
    public Clientes getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Clientes clientes) {
        this.clientes = clientes;
    }
    public Set getLineasFacturases() {
        return this.lineasFacturases;
    }
    
    public void setLineasFacturases(Set lineasFacturases) {
        this.lineasFacturases = lineasFacturases;
    }




}


