package model;
// Generated Nov 21, 2023 1:50:06 PM by Hibernate Tools 4.3.1



/**
 * LineasFacturas generated by hbm2java
 */
public class LineasFacturas  implements java.io.Serializable {


     private LineasFacturasId id;
     private Articulos articulos;
     private Facturas facturas;
     private Short cantidad;

    public LineasFacturas() {
    }

	
    public LineasFacturas(LineasFacturasId id, Articulos articulos, Facturas facturas) {
        this.id = id;
        this.articulos = articulos;
        this.facturas = facturas;
    }
    public LineasFacturas(LineasFacturasId id, Articulos articulos, Facturas facturas, Short cantidad) {
       this.id = id;
       this.articulos = articulos;
       this.facturas = facturas;
       this.cantidad = cantidad;
    }
   
    public LineasFacturasId getId() {
        return this.id;
    }
    
    public void setId(LineasFacturasId id) {
        this.id = id;
    }
    public Articulos getArticulos() {
        return this.articulos;
    }
    
    public void setArticulos(Articulos articulos) {
        this.articulos = articulos;
    }
    public Facturas getFacturas() {
        return this.facturas;
    }
    
    public void setFacturas(Facturas facturas) {
        this.facturas = facturas;
    }
    public Short getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(Short cantidad) {
        this.cantidad = cantidad;
    }


    @Override
    public String toString() {
        return id.toString();
    }
}


