/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import SwingModels.ArticulosTableModel;
import controller.FamiliasDAO;
import model.Articulos;
import model.Familias;

import javax.swing.*;
import javax.swing.table.TableModel;
import java.util.ArrayList;

/**
 *
 * @author zeglius
 */
public class ArticulosDialogPanel extends javax.swing.JPanel {

    private Familias selectedFamilia;
    private TableModel articulosTableModel;

    /**
     * Creates new form ArticulosDialogPanel
     */
    public ArticulosDialogPanel(Familias selectedFamilia) {
        initComponents();
        this.selectedFamilia = selectedFamilia;
        init();
    }

    //<editor-fold desc="My Functions">
    private void init() {
        selectedFamilia = FamiliasDAO.getFamilia(selectedFamilia);
        //noinspection unchecked
        articulosTableModel = new ArticulosTableModel(new ArrayList<Articulos>(this.selectedFamilia.getArticuloses()));
        jArticulosTable.setModel(articulosTableModel);
    }
    //</editor-fold>


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jArticulosTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jRefTextField = new javax.swing.JTextField();
        jNombreTextField = new javax.swing.JTextField();
        jPrecioTextField = new javax.swing.JTextField();
        jAddButton = new javax.swing.JButton();
        jRemoveButton = new javax.swing.JButton();

        jArticulosTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jArticulosTable);

        jLabel1.setText("Añadir articulo");

        jLabel2.setText("Ref");

        jLabel3.setText("Nombre");

        jLabel4.setText("Precio");

        jAddButton.setText("Añadir");
        jAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAddButtonActionPerformed(evt);
            }
        });

        jRemoveButton.setText("-");
        jRemoveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRemoveButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jRefTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jNombreTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPrecioTextField))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jAddButton))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRemoveButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRemoveButton))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jRefTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jNombreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jPrecioTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jAddButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jRemoveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRemoveButtonActionPerformed
        int selectedRow = jArticulosTable.getSelectedRow();
        if (selectedRow <= -1) return;
        int option = JOptionPane.showConfirmDialog(this, "Desea eliminar el articulo");
        if (option != JOptionPane.OK_OPTION) return;
        boolean removed = FamiliasDAO.removeArticuloFromFamilia(
                ((ArticulosTableModel) articulosTableModel).getArticulosList().get(selectedRow)
        );
        if (removed) {
            JOptionPane.showMessageDialog(this,"Articulo eliminado");
            init();
        } else {
            JOptionPane.showMessageDialog(this, "Error: Articulo no eliminado");
        }
    }//GEN-LAST:event_jRemoveButtonActionPerformed

    private void jAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAddButtonActionPerformed
        String refeart = jRefTextField.getText();
        String nomart = jNombreTextField.getText();
        String precio = jPrecioTextField.getText();

        boolean valid = !refeart.isBlank() && !nomart.isBlank() && !precio.isBlank();

        if (!valid) {
            JOptionPane.showMessageDialog(this,  "Alguno de los campos está vacio");
            return;
        }

        // TODO: 23/11/23 Add relationship between Articulo and lineaFacturases
        Articulos articulo = new Articulos(refeart, selectedFamilia, nomart, Short.parseShort(precio), null);
        if (FamiliasDAO.addArticuloToFamilia(articulo, selectedFamilia)) {
            JOptionPane.showMessageDialog(this, "Articulo fue añadido");
            init();
        } else {
            JOptionPane.showMessageDialog(this, "Error: Articulo no fue añadido");
        }
    }//GEN-LAST:event_jAddButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jAddButton;
    private javax.swing.JTable jArticulosTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jNombreTextField;
    private javax.swing.JTextField jPrecioTextField;
    private javax.swing.JTextField jRefTextField;
    private javax.swing.JButton jRemoveButton;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
