package view;

import controller.FacturasDAO;
import model.Facturas;
import model.LineasFacturas;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author zeglius
 */
public class LineasFacturasPane extends javax.swing.JPanel {

    private Facturas selectedFactura;
    private List<LineasFacturas> lineasFacturasList;

    /**
     * Creates new form LineasFacturasPane
     */
    public LineasFacturasPane(Facturas selectedFactura) {
        this.selectedFactura = selectedFactura;
        initComponents();
        init();
    }

    //<editor-fold desc="My functions">
    private void init() {
        selectedFactura = FacturasDAO.getFactura(selectedFactura.getNumfac());
        lineasFacturasList = new ArrayList<>((selectedFactura.getLineasFacturases()));
        DefaultTableModel model = (DefaultTableModel) jLineasFacturasTable.getModel();
        model.setRowCount(0);
        lineasFacturasList.forEach(linea -> model.addRow(new Object[]{
                linea.getArticulos().getReferart(),
                linea.getFacturas().getNumfac(),
                linea.getCantidad(),
                linea
        }));

    }
    //</editor-fold>

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jLineasFacturasTable = new javax.swing.JTable();
        jRemoveButton = new javax.swing.JButton();

        jLineasFacturasTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ref Articulo", "Num Factura", "Cantidad", "LineaID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jLineasFacturasTable);
        if (jLineasFacturasTable.getColumnModel().getColumnCount() > 0) {
            jLineasFacturasTable.getColumnModel().getColumn(3).setResizable(false);
        }

        jRemoveButton.setText("-");
        jRemoveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRemoveButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRemoveButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRemoveButton)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jRemoveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRemoveButtonActionPerformed
        int selectedOption = JOptionPane.showConfirmDialog(
                this,
                "Desea confirmar la eliminación de la linea de factura?",
                null,
                JOptionPane.OK_CANCEL_OPTION,
                JOptionPane.WARNING_MESSAGE);

        if (selectedOption == JOptionPane.OK_OPTION) {
            if (FacturasDAO.removeLineaFactura(
                    (LineasFacturas) jLineasFacturasTable.getValueAt(jLineasFacturasTable.getSelectedRow(), 3)
            )) {
                JOptionPane.showMessageDialog(this, "Factura eliminada");
            } else {
                JOptionPane.showMessageDialog(this, "Algo fue mal");
                return;
            }
            init();
        }
    }//GEN-LAST:event_jRemoveButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable jLineasFacturasTable;
    private javax.swing.JButton jRemoveButton;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
