/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.*;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.Arrays;

/**
 *
 * @author zeglius
 */
public class MainFrame extends javax.swing.JFrame {
    //<editor-fold desc="My Vars" defaultstate="collapsed">
    @SuppressWarnings("FieldCanBeLocal")
    private JFrame window;
    //</editor-fold>

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    //<editor-fold desc="My Functions" defaultstate="collapsed">

    /**
     * Disable buttons in the bar when a dialog is active.
     */
    private void disableButtons() {
        for (JButton jButton : Arrays.asList(jFamiliasButton, jClientesButton, jFacturasButton)) {
            jButton.setEnabled(false);
        }
    }

    /**
     * Enable buttons in the bar when a dialog is active.
     */
    private void enableButtons() {
        for (JButton jButton : Arrays.asList(jFamiliasButton, jClientesButton, jFacturasButton)) {
            jButton.setEnabled(true);
        }
    }

    /**
     * Open a dialog for a specific pane.
     * Must be only used for <code>FamiliasPane</code>,
     * <code>ClientesPane</code> and <code>FacturasPane</code>
     */
    private void openWindow(JPanel contentPane) {
        window = new JFrame();
        window.setContentPane(contentPane);
        window.pack();
        window.setVisible(true);
        window.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                super.windowClosing(e);
                enableButtons();
            }
        });
        disableButtons();
    }

    //</editor-fold>

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFamiliasButton = new javax.swing.JButton();
        jClientesButton = new javax.swing.JButton();
        jFacturasButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jFamiliasButton.setText("Familias");
        jFamiliasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFamiliasButtonActionPerformed(evt);
            }
        });

        jClientesButton.setText("Clientes");
        jClientesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jClientesButtonActionPerformed(evt);
            }
        });

        jFacturasButton.setText("Facturas");
        jFacturasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFacturasButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jFamiliasButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jClientesButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFacturasButton)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFamiliasButton)
                    .addComponent(jClientesButton)
                    .addComponent(jFacturasButton))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jFamiliasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFamiliasButtonActionPerformed
        // TODO add your handling code here:
        openWindow(new FamiliasPane());
    }//GEN-LAST:event_jFamiliasButtonActionPerformed


    private void jClientesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jClientesButtonActionPerformed
        // TODO add your handling code here:
        openWindow(new ClientesPane());
    }//GEN-LAST:event_jClientesButtonActionPerformed

    private void jFacturasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFacturasButtonActionPerformed
        // TODO add your handling code here:
        openWindow(new FacturasPane());
    }//GEN-LAST:event_jFacturasButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jClientesButton;
    private javax.swing.JButton jFacturasButton;
    private javax.swing.JButton jFamiliasButton;
    // End of variables declaration//GEN-END:variables
}
